Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [1]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

In [2]:
type(list_)

list

In [3]:
type(array_list)

numpy.ndarray

Yes;

Here we can see that list_ has a data type of list, while array_list has a data type of numpy.ndarray.

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [4]:
# data types of elements of list
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [5]:
# data types of elements of array_list
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [6]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
array_list = np.array(object = list_, dtype = int)

In [7]:
# data types of elements of num_list
for i in num_list:
    for j in i:
        
        print(type(j))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [8]:
# data types of elements of array_list
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Both are integer but data types of num_list is int but the data types of array_list is numpy.int64


Python integers are flexible-sized.

The numpy integers, on the other hand, are fixed-sized. This means there is a maximum value they can hold. This is defined by the number of bytes in the integer (int32 vs. int64), with more bytes holding larger numbers

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [9]:
# shape : it declares the shape of array by showing (Row , Column) of array

np.shape(num_array)

(2, 3)

In [10]:
# size : it declares the total element present in the array

np.size(num_array)

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [11]:
arr = np.zeros((3, 3))

print(type(arr))
arr

<class 'numpy.ndarray'>


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.size(arr)

9

In [13]:
np.shape(arr)

(3, 3)

In [14]:
# in term of matrix
import numpy.matlib as nm
print(type(nm.zeros((3,3))))
nm.zeros((3,3))

<class 'numpy.matrix'>


matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [15]:
print(nm.zeros((3,3)).shape)
nm.zeros((3,3)).size

(3, 3)


9

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [16]:
# in term of array
arr1=np.eye(5,5)

print(arr1)
print("")
print(np.shape(arr1))
np.size(arr1)
print(type(arr1))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

(5, 5)
<class 'numpy.ndarray'>


In [17]:
# in term of matrix
mat=nm.eye(5,5)
print(arr1)
print("")
print(nm.shape(arr1))
nm.size(arr1)
print(type(mat))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

(5, 5)
<class 'numpy.matrix'>
